[build]
  publish = "src"

[[headers]]
  for = "*.wasm"
  [headers.values]
    Content-Type = "application/wasm"

[[headers]]
  for = "*.js"
  [headers.values]
    Content-Type = "application/javascript"
